config/routes.rb
Rails.application.routes.draw do



  get 'orders/index'

  get 'simple_pages/show'

  get 'simple_pages/orders'

  get 'simple_pages/landing_page'

  resources :products
  resources :object_thrives

  root 'simple_pages#landing_page'

  get 'simple_pages/index'

  get 'simple_pages/about'

  get 'simple_pages/contact'

 resources :orders, only: [:index, :show, :create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/object_thrive.rb
class ObjectThrive < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belong_to :user
end

app/models/product.rb
class Product < ApplicationRecord
 has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/object_thrives_controller.rb
class ObjectThrivesController < ApplicationController
  before_action :set_object_thrife, only: [:show, :edit, :update, :destroy]

  # GET /object_thrives
  # GET /object_thrives.json
  def index
    @object_thrives = ObjectThrive.all
  end

  # GET /object_thrives/1
  # GET /object_thrives/1.json
  def show
  end

  # GET /object_thrives/new
  def new
    @object_thrife = ObjectThrive.new
  end

  # GET /object_thrives/1/edit
  def edit
  end

  # POST /object_thrives
  # POST /object_thrives.json
  def create
    @object_thrife = ObjectThrive.new(object_thrife_params)

    respond_to do |format|
      if @object_thrife.save
        format.html { redirect_to @object_thrife, notice: 'Object thrive was successfully created.' }
        format.json { render :show, status: :created, location: @object_thrife }
      else
        format.html { render :new }
        format.json { render json: @object_thrife.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /object_thrives/1
  # PATCH/PUT /object_thrives/1.json
  def update
    respond_to do |format|
      if @object_thrife.update(object_thrife_params)
        format.html { redirect_to @object_thrife, notice: 'Object thrive was successfully updated.' }
        format.json { render :show, status: :ok, location: @object_thrife }
      else
        format.html { render :edit }
        format.json { render json: @object_thrife.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /object_thrives/1
  # DELETE /object_thrives/1.json
  def destroy
    @object_thrife.destroy
    respond_to do |format|
      format.html { redirect_to object_thrives_url, notice: 'Object thrive was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_object_thrife
      @object_thrife = ObjectThrive.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def object_thrife_params
      params.fetch(:object_thrife, {})
    end
end

app/controllers/order_controller.rb
class OrdersController < ApplicationController

  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def destroy
  end  

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color)
    end
end

app/controllers/simple_pages_controller.rb
class SimplePagesController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def landing_page
    @featured_product = Product.first
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/object_thrives_helper.rb
module ObjectThrivesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/simple_pages_helper.rb
module SimplePagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thrive</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body id="chestnut-background">
    <nav class="navbar navbar-inverse">
       <ul>
         <a href="#" id="brand">Thrive&Fusion</a>
         <%= link_to "Orders", orders_path%>
          <%= link_to "Product", products_path%>
         <%= link_to "Contact", simple_pages_contact_path %>
         <%= link_to "About", simple_pages_about_path %>
         <%= link_to "Home", root_path %>
       </ul>
      </nav>
    <%= yield %>

    <footer class="bottom-foot">
     <span class="copywright"><a href="#">THRIVE&FUSION</a>&copy;2018 | <a href="#">TERMS-CONTACT</a></span><span class="social"><a href="#">FACEBOOK</a> | <a href="#">TWITTER</a></span>
   </footer>
  </body>
</html>

app/views/object_thrives/_form.html.erb
<%= form_with(model: object_thrife, local: true) do |form| %>
  <% if object_thrife.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(object_thrife.errors.count, "error") %> prohibited this object_thrife from being saved:</h2>

      <ul>
      <% object_thrife.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/object_thrives/edit.html.erb
<h1>Editing Object Thrife</h1>

<%= render 'form', object_thrife: @object_thrife %>

<%= link_to 'Show', @object_thrife %> |
<%= link_to 'Back', object_thrives_path %>

app/views/object_thrives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Object Thrives</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @object_thrives.each do |object_thrife| %>
      <tr>
        <td><%= link_to 'Show', object_thrife %></td>
        <td><%= link_to 'Edit', edit_object_thrife_path(object_thrife) %></td>
        <td><%= link_to 'Destroy', object_thrife, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Object Thrife', new_object_thrife_path %>

app/views/object_thrives/new.html.erb
<h1>New Object Thrife</h1>

<%= render 'form', object_thrife: @object_thrife %>

<%= link_to 'Back', object_thrives_path %>

app/views/object_thrives/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_object_thrife_path(@object_thrife) %> |
<%= link_to 'Back', object_thrives_path %>

app/views/orders/index.html.erb
<div class="container">
<div class="order-header">
  <h1>ALREADY A MEMBER SIGN IN HERE TO CONTINUE</h1>
</div>
<div class="login-form">
  <h1>LOG IN</h1>
    <form class="login">
      <br>
      <input type="text" placeholder="EMAIL ADDRESS"></input>
      <br>

      <input type="password" placeholder="PASSWORD"></input>
      <br>

      <button type="submit">SIGN IN</button>
      <br>

      <div class="reset">
        <h5 id="reset">FORGOTTEN EMAIL/PASSWORD? CLICK HERE TO RESET<button type="reset">RESET</button></h5>
      </div>
    </form>

</div>
</div>

app/views/orders/orders.html.erb
<h1>SimplePages#orders</h1>
<p>Find me in app/views/simple_pages/orders.html.erb</p>

app/views/orders/show.html.erb
<h1>SimplePages#show</h1>
<p>Find me in app/views/simple_pages/show.html.erb</p>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
  <%= f.label :color %><br>
  <%= f.text_field :color %>
</div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>


<div class="container">

<div class="producthead">
    <h1>Thrive&Fusion</h1>
  </div>
  <section class="products">

<!-- It's likely you'll need to link the card somewhere. You could add a button in the info, link the titles, or even wrap the entire card in an <a href="..."> -->
<div class="row">
  <% @products.each do |product|%>
  <div class="col-xs-12 col-sm-4">
<div class="product-card">
  <div class="product-image">
    <% if product.image_url %>
    <%= image_tag(product.image_url, class: "img-responsive") %>
    <%end%>
  <div class="product-info">
    <%= link_to product do%>

    <% end %>
    <h5><%= product.name%></h5>
  <h6>$34.99</h6>
  </a>
</div>
  </div>
</div>
</div>
<% end %>
  </div>
<!-- more products -->

</section>


</div>
<!-- more products -->

</section>

</div>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.image_url %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> -->

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>



  <%= image_tag @product.image_url, class: "foo bar", id: "baz"%>
<br>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/simple_pages/about.html.erb
<div class="container">
  <div class="about">
    <div class="about-heading">
      <img src="http://www.bswhbenefits.com/2016/ntx/PublishingImages/pages/wellness/ThriveLogo_color.png" id="about-heading">
    </div>
    <div class="container">
    <div class="about-intro">
      <p>Here at Thrive&Fusion, we take great pride in our healthy lifestyle. The LV Life is about living a Premium Lifestyle... One that is enjoyed by both Thrive&Fusion Customers and Promoters alike. The Le-Vel brand represents a culture of premium product lines, cool rewards, recognition, getaways, and exciting events. A true ultra premium lifestyle is a blend of freedom, family, financial gain, and achieving a new level in life... The Thrive&Fusion Life!</p>
      <p>Le-Vel was created and envisioned with a greater purpose, a premium plan. This plan is not to create a product, or a product line, but to build a global brand, a new icon. A brand that encompasses ultra premium products: premium product lines. The new brand, for the better lifestyle, premium-seeking consumers.</p>

<p>The largest and most successful companies in the world are extremely good at one thing. They build brands, not products. They are so good at this one focus, they can literally put their logo on anything and it is passionately accepted worldwide. As the Le-Vel vision is birthed with THRIVE, it will continue on with all of our brands and future premium products. Le-Vel will be a global giant; our logo will be on many different products, wherever you go, our logo will go with you.</p>
      <p>The quality, passion and efficacy with one product line, will flawlessly continue on to all product lines, because the true focus, our passion will always remain at its inception, The Brand: Le-Vel was created and envisioned with a greater purpose, a premium plan. This plan is not to create a product, or a product line, but to build a global brand, a new icon. A brand that encompasses ultra premium products: premium product lines. The new brand, for the better lifestyle, premium-seeking consumers.</p>

<p>The largest and most successful companies in the world are extremely good at one thing. They build brands, not products. They are so good at this one focus, they can literally put their logo on anything and it is passionately accepted worldwide. As the Le-Vel vision is birthed with THRIVE, it will continue on with all of our brands and future premium products. Le-Vel will be a global giant; our logo will be on many different products, wherever you go, our logo will go with you. The quality, passion and efficacy with one product line, will flawlessly continue on to all product lines, because the true focus, our passion will always remain at its inception, The Brand: Le-Vel.</p>

<p>To build the Premium Lifestyle Company, we knew we had to look further than just a product, we had to envision a larger purpose, a deeper reason for what we were doing. We had to create the one and only Premium Lifestyle Brand.</p>

<p>To build the Premium Lifestyle Company, we knew we had to look further than just a product, we had to envision a larger purpose, a deeper reason for what we were doing. We had to create the one and only Premium Lifestyle Brand.
</p>
      </div>
    </div>
   </div>
 </div>

app/views/simple_pages/contact.html.erb
<div class="container">
  <p id="contact-intro">Here at Thrive&Fusion we would love to hear from you about your success or talk to one our staff members regarding about Thrive&Fusion how we can help you.
  <div class="contact">
    <div class="row">
      <div class="col-sm-6 col-md-6 col-lg-6">
        <h1>Contact Us</h1>
    <div class="form-group">
      <input type="text" placeholder="First Name" class="field"></input>
      </div>
        <div class="form-group">
     <input type="text" placeholder="Last Name" class="field"></input>
    </div>
    <div class="form-group">
      <input type="text" placeholder="Email Address" class="field"></input>
  </div>
  <div class="form-group">
    <input type="text" placeholder="Contact Number" class="field"></input>
 </div>
 <button type="submit" id="submit-btn">Submit</button>
 <div class="form-group">
   <span id="contact-us">Address: 234 cherry pie JF, 58485</span>
 </div>
 <div class="form-group">
   <span id="contact-us">Contact: 854-845-1257</span>
 </div>
 <div class="form-group">
   <span id="contact-us">Email: Thrivea&FusionEnergy@gmail.com</span>
 </div>
      </div><!--col-->
      <div class="col-sm-6 col-md-6 col-lg-6">
        <img src="http://static1.squarespace.com/static/5650cf39e4b0c307d58e5d01/t/5669da7d69a91ad6eca42b5d/1511982489160/?format=1500w" id="aboutimg" class="img-responsive">
      </div><!--col-->
    </div><!--row-->
  </div>

 </div>

app/views/simple_pages/index.html.erb
<div class="container-fluid">
 <div id="myCarousel" class="carousel slide" data-ride="carousel">
   <!-- Indicators -->
   <ol class="carousel-indicators">
     <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
     <li data-target="#myCarousel" data-slide-to="1"></li>
     <li data-target="#myCarousel" data-slide-to="2"></li>
   </ol>

   <!-- Wrapper for slides -->
   <div class="carousel-inner">
     <div class="item active">
       <img src="https://cdn.le-vel.com/en/FrontEnd/Images/Home/Home-MainImage_2018_UltraPremium.jpg" id="thrive-image1" style="width:100%;">
     </div>

     <div class="item">
       <img src="https://cdn.le-vel.com/en/FrontEnd/Images/Home/Home-MainImage_2018_Welcome2pt0.jpg" id="thrive-image2">
     </div>

     <div class="item">
       <img src="https://cdn.le-vel.com/en/FrontEnd/Images/Home/Home-MainImage_2018_NameGame.jpg" id="thrive-image3" style="width:100%;">
     </div>
   </div>
 </div>
 </div>
 <div class="landing-page">
   <header class="landing-heading">
   <h1> Welcome to Thrive&Fusion Energy</h1>
 </header>
   <div class="container">
   <div class="landing-page-intro">
     <p>The THRIVE Experience is a combination of our THRIVE Premium Lifestyle Capsule, THRIVE Ultra Micronized Lifestyle Shake Mix, and our Premium Lifestyle DFT (Derma Fusion Technology). Our premium naturopathic and synergistic formula of Vitamins, Minerals, Plant Extracts, Anti-Oxidants, Enzymes, Pro-Biotics, and Amino Acids is like nothing your body has ever experienced! It's Ultra Premium at its finest. What's even better is that the experience is gender specific for Men & Women.</p>
   </div>

   <div class="landing-image4">
     <img src="http://cainbrian.com/wp-content/uploads/2014/09/Thrive-mlm-Le-Vel-products.png" class="img-responsive">
   </div>
     </div>
   <br>
   <br>

app/views/simple_pages/landing_page.html.erb
<div class="container-fluid">
 <div id="myCarousel" class="carousel slide" data-ride="carousel">
   <!-- Indicators -->
   <ol class="carousel-indicators">
     <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
     <li data-target="#myCarousel" data-slide-to="1"></li>
     <li data-target="#myCarousel" data-slide-to="2"></li>
   </ol>

   <!-- Wrapper for slides -->
   <div class="carousel-inner">
     <div class="item active">
       <img src="https://cdn.le-vel.com/en/FrontEnd/Images/Home/Home-MainImage_2018_UltraPremium.jpg" id="thrive-image1" style="width:100%;">
     </div>

     <div class="item">
       <img src="https://cdn.le-vel.com/en/FrontEnd/Images/Home/Home-MainImage_2018_Welcome2pt0.jpg" id="thrive-image2" style="width:100%;">
     </div>

     <div class="item">
       <img src="https://cdn.le-vel.com/en/FrontEnd/Images/Home/Home-MainImage_2018_NameGame.jpg" id="thrive-image3" style="width:100%;">
     </div>
   </div>
 </div>
 </div>
 <div class="landing-page">
   <header class="landing-heading">
   <h1> Welcome to Thrive&Fusion Energy</h1>
 </header>
   <div class="container">
   <div class="landing-page-intro">
     <p>The THRIVE Experience is a combination of our THRIVE Premium Lifestyle Capsule, THRIVE Ultra Micronized Lifestyle Shake Mix, and our Premium Lifestyle DFT (Derma Fusion Technology). Our premium naturopathic and synergistic formula of Vitamins, Minerals, Plant Extracts, Anti-Oxidants, Enzymes, Pro-Biotics, and Amino Acids is like nothing your body has ever experienced! It's Ultra Premium at its finest. What's even better is that the experience is gender specific for Men & Women.</p>
   </div>

   <div class="landing-image4">
     <img src="http://cainbrian.com/wp-content/uploads/2014/09/Thrive-mlm-Le-Vel-products.png" class="img-responsive">
   </div>
     </div>
   <br>
   <br>